### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by ghost** [ksafin/DynamicEconomy#17]
Hi there,

I am getting this occasionally in my log. I am not sure why really. I tried to ask people what they buy but nobody replies and it doesn't output the command ran to the console so I cant see it even.

Thanks =)

<pre>
2012-03-06 14:30:52 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'buy' in plugin DynamicEconomy v.8.02
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:461)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:818)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:778)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:761)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:112)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at me.ksafin.DynamicEconomy.Transaction.getDmg(Transaction.java:307)
    at me.ksafin.DynamicEconomy.Transaction.buy(Transaction.java:274)
    at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:248)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more
</pre>

**Comment by ghost** [comment]
Ok I found another one that maybe would help. It seemed to be when they ran a command that doesn't exist or something. This time I can see the command because I actually have what they typed redirected through CommandHelper

<pre>
2012-03-06 20:06:31 [INFO] CH: Running original command on player playername ----> /shops xp
2012-03-06 20:06:31 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'dynamiceconomy' in plugin DynamicEconomy v.8.02
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:461)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:818)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:778)
    at org.bukkit.craftbukkit.entity.CraftPlayer.chat(CraftPlayer.java:235)
    at com.laytonsmith.abstraction.bukkit.BukkitMCPlayer.chat(BukkitMCPlayer.java:54)
    at com.laytonsmith.core.AliasCore$1.done(AliasCore.java:119)
    at com.laytonsmith.core.MScriptCompiler.execute(MScriptCompiler.java:527)
    at com.laytonsmith.core.Script.run(Script.java:179)
    at com.laytonsmith.core.AliasCore.alias(AliasCore.java:104)
    at com.laytonsmith.commandhelper.CommandHelperListener.runAlias(CommandHelperListener.java:79)
    at com.laytonsmith.commandhelper.CommandHelperListener.onPlayerCommandPreprocess(CommandHelperListener.java:119)
    at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:811)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:778)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:761)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:112)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NumberFormatException: For input string: "xp"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:492)
    at java.lang.Integer.parseInt(Integer.java:527)
    at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.commandList(DynamicEconomyCommandExecutor.java:684)
    at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:201)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 28 more
</pre>

**Comment by ksafin** [comment]
I can't replicate either error :/

The first error means that the user must be purchasing something with an ID > 1000, however its actually invalid.. so I'm not sure what's going on there.

As for the second error, I don't get what's going on.
They're passing "xp" as an argument to /dynamiceconomy
However, /dynamiceconomy only takes one argument. It takes an integer page number.
The XP causes an Integer Parse error.

**Comment by ghost** [comment]
Ah, I see. I don't know what they were doing in the first error either but it would be cool if there didn't have to be an error. And the 2nd one I guess they were just trying to buy xp because I had an xp plugin called xpShop on but it was somewhat buggy so I disabled it for a bit and they must have tried using this plugin to get some xp.

At any rate, I don't think a severe error should ever happen. Especially since some server wrappers will restart the server on a [SEVERE] error. Mine can but I have that disabled since it seems like it could be an easy way to grief the server but it seems like a good feature in some instances. Maybe with some tweaks and additional checks it could be useful.

I understand this is a work in progress so no worries. I am just glad I could help test a little and whatnot. Thanks for the great work =)
