### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by angelofdev** [ksafin/DynamicEconomy#19]
Plugin version: .8.02

I don't know how this happens but it happens frequently. 
The plugin seems to work fine but the error is always displayed in the console.

2012-03-10 11:16:53 [SEVERE] Could not pass event PlayerInteractEvent to DynamicEconomy
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:168)
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:138)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:886)
at net.minecraft.server.Packet18ArmAnimation.handle(SourceFile:38)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:112)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
at me.ksafin.DynamicEconomy.DynamicEconomyPlayerListener.onPlayerInteract(DynamicEconomyPlayerListener.java:69)
at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 12 more

**Comment by ksafin** [comment]
Fixed.

Turns out this happens when players right click the air; such an action return a null and blows up the PlayerInteractEvent.

Fixed with an if statement to check for null
