### ISSUE TITLE
Caused by: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by gonimar** [ksafin/DynamicEconomy#2]
2012-02-23 19:49:25 [INFO] [DynamicEconomy] Loading DynamicEconomy v.6.1.
2012-02-23 19:49:25 [INFO] [DynamicEconomy] Vault Economy hooked
2012-02-23 19:49:25 [INFO] [DynamicEconomy] Vault Permissions hooked
2012-02-23 19:49:27 [INFO] [DynamicEconomy] Items database loaded.
2012-02-23 19:49:27 [INFO] [DynamicEconomy] Region database loaded.
2012-02-23 19:49:27 [INFO] [DynamicEconomy] Core Config loaded.
2012-02-23 19:49:27 [INFO] [DynamicEconomy] CommandExec Economy set
2012-02-23 19:49:27 [INFO] [DynamicEconomy] CommandExec Permissions set

2012-02-23 22:26:24 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'debuy' in plugin DynamicEconomy v.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:402)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:784)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:744)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:732)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NumberFormatException: For input string: "1,01"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1242)
        at java.lang.Double.valueOf(Double.java:492)
        at me.ksafin.DynamicEconomy.Transaction.buy(Transaction.java:192)
        at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:196)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more

**Comment by ksafin** [comment]
Have not been able to replicate the error.

If error persists, please comment back with screenshots & commands entered, as well as logs.
