### ISSUE TITLE
 [WARNING] Task of 'DynamicEconomy' generated an exception

### ISSUE THREAD

**Issue by ghost** [ksafin/DynamicEconomy#37]
2012-03-20 11:39:36 [WARNING] Task of 'DynamicEconomy' generated an exception
java.lang.NumberFormatException: For input string: "0,05"
    at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
    at java.lang.Double.valueOf(Unknown Source)
    at me.ksafin.DynamicEconomy.loan.dynamicInterest(loan.java:290)
    at me.ksafin.DynamicEconomy.DynamicEconomy$1.run(DynamicEconomy.java:469)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
2012-03-20 11:39:46 [WARNING] Task of 'DynamicEconomy' generated an exception
java.lang.NumberFormatException: For input string: "?"
    at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
    at java.lang.Double.valueOf(Unknown Source)
    at me.ksafin.DynamicEconomy.loan.dynamicInterest(loan.java:290)
    at me.ksafin.DynamicEconomy.loan.run(loan.java:316)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

I got this when i start my server a the end of the log... its okay but when i buy i spend money but i got no item...

**Comment by March75** [comment]
The same with my server. Even with all other AddOns "switched off" (except vault and essentials) the exception makes trouble.

**Comment by ksafin** [comment]
I think this is fixed in the latest version with some Locale precautions I put in. Open another ticket if it persists.
