### ISSUE TITLE
Using /dyneconupdate thru console

### ISSUE THREAD

**Issue by LordRalex** [ksafin/DynamicEconomy#38]
When using the command thru the console, you get a null pointer because you assumed the CommandSender was a player, when the console is not.

2012-03-20 16:54:18 [WARNING] Unexpected exception while parsing console command
org.bukkit.command.CommandException: Unhandled exception executing command 'dyneconupdate' in plugin DynamicEconomy v.8.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:469)
    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:465)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:568)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
    at net.milkbowl.vault.permission.Permission.has(Permission.java:101)
    at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:428)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 7 more

I can fork it and do a pull request if you want me to fix this

**Comment by ksafin** [comment]
I'll change all of my commands to work with console (except like, buy and sell).

... eventually.

**Comment by LordRalex** [comment]
It is a relatively easy fix. I can fork it and do a pull request if you want me to do it?

It is just that the command should be use-able in the console, seems the best place to use it

**Comment by ksafin** [comment]
My code isn't up to date

**Comment by LordRalex** [comment]
<.<

**Comment by ksafin** [comment]
Fixed
