### ISSUE TITLE
1.2.4 Error

### ISSUE THREAD

**Issue by DaneEveritt** [ksafin/DynamicEconomy#48]
``` java
19:22:18 [WARNING] Task of 'DynamicEconomy' generated an exception
java.lang.NullPointerException
        at me.ksafin.DynamicEconomy.RandomEvent.run(RandomEvent.java:72)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
```

**Comment by ksafin** [comment]
I'll check it out

**Comment by ksafin** [comment]
Do you have a type specified for all of your events? This happens to be a line that accesses the "TYPE" field of an event.

**Comment by ksafin** [comment]
Closed due to no response, may be re-opened if response is met, I can't seem to reproduce the error.
