### ISSUE TITLE
Console error with addstock/removestock

### ISSUE THREAD

**Issue by Bronski** [ksafin/DynamicEconomy#53]
It seems to add/remove the item in question, but the error is coming up red in-game and the one below in the console.  Maybe it's related to these 2 signs that also don't seem to be working:

dynamicsign
ironingot
price,stock

dynamicsign
goldingot
price

bukkit built 2060/dyneco8.31:

07:40:58 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'addstock' in plugin DynamicEconomy v.8.31
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:469)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:906)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:866)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:849)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:116)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
        at me.ksafin.DynamicEconomy.dataSigns.checkForUpdates(dataSigns.java:140)
        at me.ksafin.DynamicEconomy.Transaction.addStock(Transaction.java:766)
        at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:334)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more
07:41:01 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'removestock' in plugin DynamicEconomy v.8.31
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:469)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:906)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:866)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:849)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:116)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
        at me.ksafin.DynamicEconomy.dataSigns.checkForUpdates(dataSigns.java:140)
        at me.ksafin.DynamicEconomy.Transaction.removeStock(Transaction.java:796)
        at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:369)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more

**Comment by ksafin** [comment]
You cannot use "price,stock" in a sign. You can only choose one or the other.

That's why the first sign isn't functioning, and probably the source of the error.
