### ISSUE TITLE
Task of 'DynamicEconomy' generated an exception

### ISSUE THREAD

**Issue by blackdevil72** [ksafin/DynamicEconomy#61]
2012-03-30 23:58:23 [WARNING] Task of 'DynamicEconomy' generated an exception
java.lang.NumberFormatException: For input string: "0,05"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1222)
    at java.lang.Double.valueOf(Double.java:475)
    at me.ksafin.DynamicEconomy.loan.dynamicInterest(loan.java:290)
    at me.ksafin.DynamicEconomy.DynamicEconomy$1.run(DynamicEconomy.java:469)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
2012-03-30 23:58:31 [WARNING] Task of 'DynamicEconomy' generated an exception
java.lang.NumberFormatException: For input string: "∞"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1222)
    at java.lang.Double.valueOf(Double.java:475)
    at me.ksafin.DynamicEconomy.loan.dynamicInterest(loan.java:290)
    at me.ksafin.DynamicEconomy.loan.run(loan.java:316)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by ghost** [comment]
i got the same problem... nobody seem to know.

**Comment by blackdevil72** [comment]
Maybe it is from less compatibility with an other plugin

**Comment by ksafin** [comment]
Yes some people have been getting this for a while and I honestly have no clue what it is.

It seems to occur based on your server, settings, and locale.

Some locales utilize commas (,) instead of decimals (.) for currencies, therefore causing issues like this.

However, the fact that you have an infinity symbol in there is beyond me..

**Comment by blackdevil72** [comment]
Hi I have maybe found the plugin that cause this.

Essentials use as economy plugin, yesterday I installed iConomy and this error never ocure again. But I got a new strange thing aferter serveral hours the serveur crash without any error log. it juste crash and its impossible to use stop command or something else and the client got an "end of stream" error. I got to kill de process in the terminal.

**Comment by ksafin** [comment]
I'm looking into an issue similar to that right now with some other users. I'll let you know about the crash.

Glad you found Essentials to be the problem though, I'll look into that.
