### ISSUE TITLE
Unexpected exception while parsing console command

### ISSUE THREAD

**Issue by noxgandhi** [ksafin/DynamicEconomy#78]
whenever i try to use any of the dynecon commands i get the same error. Vault is installed. both are latest version:

2012-04-13 18:26:06 [WARNING] Unexpected exception while parsing console command org.bukkit.command.CommandException: Unhandled exception executing command 'dynecon' in plugin DynamicEconomy v.8.5 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42) at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166) at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473) at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:469) at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:596) at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:565) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449) at net.minecraft.server.ThreadServerApplication.run(SourceFile:492) Caused by: java.lang.NullPointerException at net.milkbowl.vault.permission.Permission.has(Permission.java:101) at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:215) at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40) ... 7 more

also to mention: 
2012-04-13 18:25:21 [INFO] [DynamicEconomy] Vault Economy not hooked

**Comment by semibreve42** [comment]
Not sure if the same or different, but I get this error whenever someone uses a command on 8.5:

16:43:26 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'desell' in plugin DynamicEconomy v.8.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:103)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:169)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
        at org.bukkit.Location.getBlock(Location.java:82)
        at me.ksafin.DynamicEconomy.dataSigns.updateItem(dataSigns.java:195)
        at me.ksafin.DynamicEconomy.dataSigns.checkForUpdates(dataSigns.java:143)
        at me.ksafin.DynamicEconomy.Transaction.sell(Transaction.java:931)
        at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:279)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 14 more

**Comment by noxgandhi** [comment]
my version of DE doesnt support a command called desell, but what we've found out is: that you cant execute DE commands via console. besides you need vault AND essentials. vault 1.2.4 works fine with the most recent version of DE, vault 1.2.5 causes extreme lags.

**Comment by semibreve42** [comment]
That error happens regardless of who uses the command - I have not tried them from the console.  

desell and debuy are the alternative commands for sell and buy, which can be turned on in the config - my donation plugin uses buy, so I have to use desell and debuy.  

I'm pretty sure I was on 1.2.13, but I've replaced it with 1.2.14 to see if that makes a difference - find out after the next server restart.

Also I don't think essentials is a requirement?  I use iconomy for my economy plugin, not essentials.
