### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by BONNe** [ksafin/DynamicEconomy#85]
Some problem with console... you cannot reload config from it, but for me it is usefull to reload from console, because it is faster then joining game and reload from there...
I often add some new events or change something so "dynamiceconomyreloadconfig" is important command for me

2012-04-23 03:15:34 [WARNING] Unexpected exception while parsing console command
org.bukkit.command.CommandException: Unhandled exception executing command 'dynamiceconomyreloadconfig' in plugin DynamicEconomy v.8.5
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:469)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:596)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:565)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at net.milkbowl.vault.permission.Permission.has(Permission.java:101)
    at me.ksafin.DynamicEconomy.DynamicEconomyCommandExecutor.onCommand(DynamicEconomyCommandExecutor.java:349)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 7 more

**Comment by ksafin** [comment]
/dynamiceconomyreloadconfig is now a console-accessible command,
