### ISSUE TITLE
An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by squidicuzz** [ksafin/DynamicEconomy#87]
2012-04-27 05:25:58 [INFO] 1:0
2012-04-27 05:25:58 [INFO] Name: 1
2012-04-27 05:25:58 [SEVERE] org.bukkit.command.CommandException: Unhandled exception executing command 'sell' in plugin DynamicEconomy v.8.5
2012-04-27 05:25:58 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-04-27 05:25:58 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
2012-04-27 05:25:58 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
2012-04-27 05:25:58 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:103)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
2012-04-27 05:25:58 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:169)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
2012-04-27 05:25:58 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-04-27 05:25:58 [SEVERE] Caused by: java.lang.NullPointerException

It is doing this for every item when buying and selling.  The command still seems to work though.

**Comment by squidicuzz** [comment]
I figured it out!

This error shows up if there are two dynamicsign's of the same item.  Might want to make it so only one sign of each item can placed at a time, or to have it handle more than one dynamicsign.

**Comment by ksafin** [comment]
Can you post the second error? (There's one beginning at the very end of your paste, the NullPointerException). 

Two dynamicsigns for one item work fine, so I don't see how that oculd be it.

**Comment by ksafin** [comment]
Closed because of no response

**Comment by squidicuzz** [comment]
Sorry, I couldn't duplicate it again.. it seems to be resolved :s
