### ISSUE TITLE
Loan causing error sending color message

### ISSUE THREAD

**Issue by EmpathDemon** [ksafin/DynamicEconomy#95]
If I take out a loan, then log out before the loan comes due, my console reports the following (the loan payment is properly deducted):

2012-05-25 15:04:03 [INFO] [Extras] Error sending coloured message! Caused by plugin : DynamicEconomy
2012-05-25 15:04:03 [SEVERE] java.lang.NullPointerException
2012-05-25 15:04:03 [SEVERE]    at couk.Adamki11s.Extras.Colour.ExtrasColour.sendColouredMessage(ExtrasColour.java:17)
2012-05-25 15:04:03 [SEVERE]    at me.ksafin.DynamicEconomy.loan.run(loan.java:371)
2012-05-25 15:04:03 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
2012-05-25 15:04:03 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:524)
2012-05-25 15:04:03 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:450)
2012-05-25 15:04:03 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by ksafin** [comment]
Fixed; added null-check for player to determine if they are offline or not.
